## Numpy
Numpy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

In [2]:
import numpy as np
arr1 = np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))
print(arr1.shape)



[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [4]:
## Reshaping the arrays
arr2 = np.array([1,2,3,4,5,6])
arr2.reshape(1,6)


array([[1, 2, 3, 4, 5, 6]])

In [ ]:
## 2-D Array
arr2 = np.array([[1,2,3,4,5,6],[2,3,4,5,6,7]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5 6]
 [2 3 4 5 6 7]]
(2, 6)


In [12]:
np.arange(0,50,5).reshape(2,5)

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45]])

In [14]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
# Creating the identity matrix
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
## For getting the dimension of the array
arr2.ndim

2

In [18]:
## Size: number of elements present in the array
arr2.size

12

In [19]:
## Size of items(in bytes)
arr2.itemsize

8

# Numpy Vectorized Operation

In [20]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

In [22]:
### Element wise addition
print("Addition: ", arr1+arr2)

### Element wise subtraction
print("Subtraction: ", arr1-arr2)

### Element wise multiplication
print("Multiplication: ", arr1*arr2)

### Element wise division
print("Division: ", arr1/arr2)


Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [25]:
### Universal Function
arr=np.array([2,3,4,5,6])

## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sin
print(np.sin(arr))

## log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


## Universal Functions (ufunctions)

In [27]:
## Array slicing and indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
arr[0]

array([1, 2, 3, 4])

In [29]:
arr[0][1]

np.int64(2)

In [31]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
arr[0:, 2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [34]:
arr[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [39]:
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [40]:
## Modify array elements
arr[0,0]= 100

In [41]:
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [42]:
arr[1:]=200
arr

array([[100,   2,   3,   4],
       [200, 200, 200, 200],
       [200, 200, 200, 200]])

In [44]:
### Statistical concepts-- Normalization
## To have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

## Calculate the mean and standard deviation 
mean = np.mean(data)
std_dev = np.std(data)

## Normalize the data
normalized_data = (data-mean)/std_dev
print("Normalized data: ", normalized_data)

var = np.var(data)
print("Variance of data: ", var)

Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
Variance of data:  2.0


In [49]:
data[(data<5) & (data>2)]


array([3, 4])